
on:
  port: 8080
  address: 0.0.0.0

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/yungo?characterEncoding=utf8&useSSL=true
  username: root
  password: mysql
  options: logger=Slf4JLogger

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect